--
-- ER/Studio Data Architect 9.0 SQL Code Generation
-- Project :      Geochemistry_Simplified_Model_1.DM1
--
-- Date Created : Tuesday, November 06, 2012 17:39:41
-- Target DBMS : MySQL 5.x
--

-- 
-- TABLE: CHM_ANALYSIS 
--

CREATE TABLE CHM_ANALYSIS(
    CHM_ANALYSIS_ID     DECIMAL(38, 0)    NOT NULL,
    PREPERATION_CODE    VARCHAR(5),
    METHOD_CODE         VARCHAR(7),
    CHM_BATCH_ID        DECIMAL(38, 0),
    DATE_REQUESTED      DATE              NOT NULL,
    DATE_RECEIVED       DATE,
    DATE_REPORTED       DATE,
    PRIMARY KEY (CHM_ANALYSIS_ID)
)ENGINE=MYISAM
COMMENT='Batch analysis details ie method, preparation and lab used'
;

-- 
-- TABLE: CHM_ANALYTE_DETERMINATION 
--

CREATE TABLE CHM_ANALYTE_DETERMINATION(
    CHM_DETERMINATION_ID    DECIMAL(38, 0)    NOT NULL,
    CHM_BATCH_ID            DECIMAL(38, 0),
    SAMPLE_ID               DECIMAL(38, 0),
    CHM_LIMIT_ID            CHAR(10),
    ABUNDANCE               DECIMAL(10, 0)    NOT NULL,
    ORIGINAL_RESULT         VARCHAR(100),
    ORIGINAL_UNIT_CODE      VARCHAR(20)       NOT NULL,
    PRIMARY KEY (CHM_DETERMINATION_ID)
)ENGINE=MYISAM
COMMENT='Results of geochemical analysis on a batch of samples.'
;

-- 
-- TABLE: CHM_ANALYTE_DETERMINATION_LIMITS 
--

CREATE TABLE CHM_ANALYTE_DETERMINATION_LIMITS(
    CHM_LIMIT_ID             CHAR(10)          NOT NULL,
    ANALYTE_CODE             VARCHAR(7),
    CHM_ANALYSIS_ID          DECIMAL(38, 0),
    DETECTION_LOWER_LIMIT    DECIMAL(13, 6),
    DETECTION_UPPER_LIMIT    DECIMAL(13, 6),
    DETECTION_UNIT_CODE      VARCHAR(20)       NOT NULL,
    PRIMARY KEY (CHM_LIMIT_ID)
)ENGINE=MYISAM
COMMENT='Detection limits for each analysis record in CHM_ANALYSIS.'
;

-- 
-- TABLE: CHM_BATCH 
--

CREATE TABLE CHM_BATCH(
    CHM_BATCH_ID       DECIMAL(38, 0)    NOT NULL,
    LABORATORY_CODE    VARCHAR(5),
    LAB_BATCH_ID       VARCHAR(50),
    DATE_REGISTERED    DATE              NOT NULL,
    PRIMARY KEY (CHM_BATCH_ID)
)ENGINE=MYISAM
COMMENT='A table containing a batch of samples registered as a batch by a laboratory.'
;

-- 
-- TABLE: CHM_BATCH_SAMPLE 
--

CREATE TABLE CHM_BATCH_SAMPLE(
    CHM_BATCH_ID    DECIMAL(38, 0)    NOT NULL,
    SAMPLE_ID       DECIMAL(38, 0)    NOT NULL,
    PRIMARY KEY (CHM_BATCH_ID, SAMPLE_ID)
)ENGINE=MYISAM
COMMENT='Linking table to record which samples were batched together'
;

-- 
-- TABLE: CHM_SAMPLE 
--

CREATE TABLE CHM_SAMPLE(
    SAMPLE_ID         DECIMAL(38, 0)    NOT NULL,
    SITE_ID           DECIMAL(38, 0)    NOT NULL,
    COLLECTED_DATE    DATETIME,
    PRIMARY KEY (SAMPLE_ID)
)ENGINE=MYISAM
COMMENT='Index table of geochemical samples.'
;

-- 
-- TABLE: CHM_SITE 
--

CREATE TABLE CHM_SITE(
    SITE_ID      DECIMAL(38, 0)    NOT NULL,
    X            DECIMAL(10, 0)    NOT NULL,
    Y            DECIMAL(10, 0)    NOT NULL,
    EPSG_CODE    VARCHAR(10)       NOT NULL,
    PRIMARY KEY (SITE_ID)
)ENGINE=MYISAM
COMMENT='Location from which a sample was collected.'
;

-- 
-- TABLE: DIC_ANALYSIS_METHOD 
--

CREATE TABLE DIC_ANALYSIS_METHOD(
    CODE           VARCHAR(7)      NOT NULL,
    TRANSLATION    VARCHAR(50)     NOT NULL,
    DESCRIPTION    VARCHAR(250)    NOT NULL,
    STATUS         CHAR(1)         DEFAULT 'C' NOT NULL,
    PRIMARY KEY (CODE)
)ENGINE=MYISAM
COMMENT='Dictionary containing methods of chemical analysis.'
;

-- 
-- TABLE: DIC_ANALYSIS_PREP 
--

CREATE TABLE DIC_ANALYSIS_PREP(
    CODE           VARCHAR(5)      NOT NULL,
    TRANSLATION    VARCHAR(60)     NOT NULL,
    DESCRIPTION    VARCHAR(250)    NOT NULL,
    STATUS         CHAR(1)         DEFAULT 'C' NOT NULL,
    PRIMARY KEY (CODE)
)ENGINE=MYISAM
COMMENT='A dictionary of preparations that are undertaken in a laboratory on a batch of samples'
;

-- 
-- TABLE: DIC_ANALYTE 
--

CREATE TABLE DIC_ANALYTE(
    CODE                  VARCHAR(7)       NOT NULL,
    QUANTITY_UNIT_CODE    VARCHAR(20),
    TRANSLATION           VARCHAR(25)      NOT NULL,
    DESCRIPTION           VARCHAR(240)     NOT NULL,
    STATUS                CHAR(1)          DEFAULT 'C' NOT NULL,
    ATOMIC_NUMBER         DECIMAL(3, 0),
    WEIGHT                DECIMAL(6, 3),
    PRIMARY KEY (CODE)
)ENGINE=MYISAM
COMMENT='Dictionary list of geochemical analytes'
;

-- 
-- TABLE: DIC_LABORATORY 
--

CREATE TABLE DIC_LABORATORY(
    CODE           VARCHAR(5)      NOT NULL,
    TRANSLATION    VARCHAR(60)     NOT NULL,
    DESCRIPTION    VARCHAR(200)    NOT NULL,
    STATUS         CHAR(1)         DEFAULT 'C' NOT NULL,
    PRIMARY KEY (CODE)
)ENGINE=MYISAM
COMMENT='Dictionary containing a list of laboratories that could be used for chemical analysis.'
;

-- 
-- TABLE: DIC_UNIT_OF_MEASURE 
--

CREATE TABLE DIC_UNIT_OF_MEASURE(
    CODE                       VARCHAR(20)       NOT NULL,
    DESCRIPTION                VARCHAR(200)      NOT NULL,
    TRANSLATION                VARCHAR(80),
    ABBREVIATION               VARCHAR(15),
    EPSG_CODE                  VARCHAR(20),
    DATA_SOURCE                VARCHAR(20),
    TARGET_UOM_CODE            VARCHAR(20),
    CONV_FACTOR_NUMERATOR      DECIMAL(20, 5),
    CONV_FACTOR_DENOMINATOR    DECIMAL(20, 5),
    UNIT_OF_MEAS_DIMENSION     VARCHAR(50)       
                               CHECK (UNIT_OF_MEAS_DIMENSION in 
('all','length','angle','scale','volumetric rate','mass rate','temperature','mass','volume','charge per mass',
'time','Dimensionless','electric conductivity','volumetric mass','turbidity','area', 'density', '?', 'pressure',
'ratio', 'resistivity', 'slowness', 'velocity'
)),
    REMARKS                    VARCHAR(255),
    ORIG_INFORMATION_SOURCE    VARCHAR(255),
    STATUS                     CHAR(1)           DEFAULT 'C' NOT NULL
                               CHECK (status in ('C','O')),
    PRIMARY KEY (CODE)
)ENGINE=MYISAM
COMMENT='Dictionary table to store list of measurement units'
;

-- 
-- TABLE: CHM_ANALYSIS 
--

ALTER TABLE CHM_ANALYSIS ADD CONSTRAINT RefCHM_BATCH81 
    FOREIGN KEY (CHM_BATCH_ID)
    REFERENCES CHM_BATCH(CHM_BATCH_ID)
;

ALTER TABLE CHM_ANALYSIS ADD CONSTRAINT RefDIC_ANALYSIS_METHOD91 
    FOREIGN KEY (METHOD_CODE)
    REFERENCES DIC_ANALYSIS_METHOD(CODE)
;

ALTER TABLE CHM_ANALYSIS ADD CONSTRAINT RefDIC_ANALYSIS_PREP101 
    FOREIGN KEY (PREPERATION_CODE)
    REFERENCES DIC_ANALYSIS_PREP(CODE)
;


-- 
-- TABLE: CHM_ANALYTE_DETERMINATION 
--

ALTER TABLE CHM_ANALYTE_DETERMINATION ADD CONSTRAINT RefDIC_UNIT_OF_MEASURE601 
    FOREIGN KEY (ORIGINAL_UNIT_CODE)
    REFERENCES DIC_UNIT_OF_MEASURE(CODE)
;

ALTER TABLE CHM_ANALYTE_DETERMINATION ADD CONSTRAINT RefCHM_ANALYTE_DETERMINATION_LIMITS281 
    FOREIGN KEY (CHM_LIMIT_ID)
    REFERENCES CHM_ANALYTE_DETERMINATION_LIMITS(CHM_LIMIT_ID)
;

ALTER TABLE CHM_ANALYTE_DETERMINATION ADD CONSTRAINT RefCHM_BATCH_SAMPLE291 
    FOREIGN KEY (CHM_BATCH_ID, SAMPLE_ID)
    REFERENCES CHM_BATCH_SAMPLE(CHM_BATCH_ID, SAMPLE_ID)
;


-- 
-- TABLE: CHM_ANALYTE_DETERMINATION_LIMITS 
--

ALTER TABLE CHM_ANALYTE_DETERMINATION_LIMITS ADD CONSTRAINT RefDIC_UNIT_OF_MEASURE591 
    FOREIGN KEY (DETECTION_UNIT_CODE)
    REFERENCES DIC_UNIT_OF_MEASURE(CODE)
;

ALTER TABLE CHM_ANALYTE_DETERMINATION_LIMITS ADD CONSTRAINT RefCHM_ANALYSIS121 
    FOREIGN KEY (CHM_ANALYSIS_ID)
    REFERENCES CHM_ANALYSIS(CHM_ANALYSIS_ID)
;

ALTER TABLE CHM_ANALYTE_DETERMINATION_LIMITS ADD CONSTRAINT RefDIC_ANALYTE131 
    FOREIGN KEY (ANALYTE_CODE)
    REFERENCES DIC_ANALYTE(CODE)
;


-- 
-- TABLE: CHM_BATCH 
--

ALTER TABLE CHM_BATCH ADD CONSTRAINT RefDIC_LABORATORY311 
    FOREIGN KEY (LABORATORY_CODE)
    REFERENCES DIC_LABORATORY(CODE)
;


-- 
-- TABLE: CHM_BATCH_SAMPLE 
--

ALTER TABLE CHM_BATCH_SAMPLE ADD CONSTRAINT RefCHM_BATCH241 
    FOREIGN KEY (CHM_BATCH_ID)
    REFERENCES CHM_BATCH(CHM_BATCH_ID)
;

ALTER TABLE CHM_BATCH_SAMPLE ADD CONSTRAINT RefCHM_SAMPLE251 
    FOREIGN KEY (SAMPLE_ID)
    REFERENCES CHM_SAMPLE(SAMPLE_ID)
;


-- 
-- TABLE: CHM_SAMPLE 
--

ALTER TABLE CHM_SAMPLE ADD CONSTRAINT RefCHM_SITE11 
    FOREIGN KEY (SITE_ID)
    REFERENCES CHM_SITE(SITE_ID)
;


-- 
-- TABLE: DIC_ANALYTE 
--

ALTER TABLE DIC_ANALYTE ADD CONSTRAINT RefDIC_UNIT_OF_MEASURE641 
    FOREIGN KEY (QUANTITY_UNIT_CODE)
    REFERENCES DIC_UNIT_OF_MEASURE(CODE)
;


-- 
-- TABLE: DIC_UNIT_OF_MEASURE 
--

ALTER TABLE DIC_UNIT_OF_MEASURE ADD CONSTRAINT DIC_UNIT_OF_MEASURE_FK1 
    FOREIGN KEY (TARGET_UOM_CODE)
    REFERENCES DIC_UNIT_OF_MEASURE(CODE)
;


