--
-- ER/Studio Data Architect 9.0 SQL Code Generation
-- Project :      Geochemistry_Simplified_Model_1.DM1
--
-- Date Created : Wednesday, September 02, 2015 09:56:26
-- Target DBMS : PostgreSQL 8.0
--

-- 
-- TABLE: "CHM_ANALYSIS" 
--

CREATE TABLE "CHM_ANALYSIS"(
    "CHM_ANALYSIS_ID"   numeric(38, 0)    NOT NULL,
    "PREPERATION_CODE"  varchar(5),
    "METHOD_CODE"       varchar(7),
    "CHM_BATCH_ID"      numeric(38, 0),
    "DATE_REQUESTED"    date              NOT NULL,
    "DATE_RECEIVED"     date,
    "DATE_REPORTED"     date
)
;



COMMENT ON TABLE "CHM_ANALYSIS" IS 'Batch analysis details ie method, preparation and lab used'
;
COMMENT ON COLUMN "CHM_ANALYSIS"."CHM_ANALYSIS_ID" IS 'PK. Unique ID for each analysis record for each batch. Generated by database.'
;
COMMENT ON COLUMN "CHM_ANALYSIS"."PREPERATION_CODE" IS 'FK. Identifier for each preparation method, used as part of a composite key in CHM_ANALYSIS.'
;
COMMENT ON COLUMN "CHM_ANALYSIS"."METHOD_CODE" IS 'FK. Identifier for each method, used as part of a composite key in CHM_ANALYSIS.'
;
COMMENT ON COLUMN "CHM_ANALYSIS"."CHM_BATCH_ID" IS 'FK. Unique ID for a batch generated by database, used as part of a composite key in CHM_ANALYSIS.'
;
COMMENT ON COLUMN "CHM_ANALYSIS"."DATE_REQUESTED" IS 'Date on which the analysis was requested.'
;
COMMENT ON COLUMN "CHM_ANALYSIS"."DATE_RECEIVED" IS 'Date on which the prepared batch of samples was received by the analytical laboratory.'
;
COMMENT ON COLUMN "CHM_ANALYSIS"."DATE_REPORTED" IS 'Date on which the analyte determinations were reported by the analytical laboratory.'
;
-- 
-- TABLE: "CHM_ANALYTE_DETERMINATION" 
--

CREATE TABLE "CHM_ANALYTE_DETERMINATION"(
    "CHM_DETERMINATION_ID"  numeric(38, 0)    NOT NULL,
    "CHM_BATCH_ID"          numeric(38, 0),
    "SAMPLE_ID"             numeric(38, 0),
    "CHM_LIMIT_ID"          char(10),
    "ABUNDANCE"             numeric(10, 0)    NOT NULL,
    "ORIGINAL_RESULT"       varchar(100),
    "ORIGINAL_UNIT_CODE"    varchar(20)       NOT NULL
)
;



COMMENT ON TABLE "CHM_ANALYTE_DETERMINATION" IS 'Results of geochemical analysis on a batch of samples.'
;
COMMENT ON COLUMN "CHM_ANALYTE_DETERMINATION"."CHM_BATCH_ID" IS 'FK. Unique ID for a batch as stored in the CHM_BATCH table.'
;
COMMENT ON COLUMN "CHM_ANALYTE_DETERMINATION"."SAMPLE_ID" IS 'FK. This is the unique ID from the CHM_SAMPLE table.'
;
COMMENT ON COLUMN "CHM_ANALYTE_DETERMINATION"."CHM_LIMIT_ID" IS 'FK. This unique ID in CHM_ANALYTLE_DETERMINATION_LIMITS provides a way of validating the ORIGINAL_RESULT value.'
;
COMMENT ON COLUMN "CHM_ANALYTE_DETERMINATION"."ABUNDANCE" IS 'The analyte abundance in parts per million. This may be populated directly if the value is known in ppm or by some conversion of the ORIGINAL_VALUE. See ORIGINAL_UNIT and ORIGINAL_UNIT_CODE for completeness.'
;
COMMENT ON COLUMN "CHM_ANALYTE_DETERMINATION"."ORIGINAL_RESULT" IS 'The original value reported by the laboratory for each analyte, see ORIGINAL_UNIT_CODE for unit type.  The standardised results column ABUNDANCE is holds the value in ppm.'
;
COMMENT ON COLUMN "CHM_ANALYTE_DETERMINATION"."ORIGINAL_UNIT_CODE" IS 'FK. Unique identifier in DIC_UNIT_OF_MEASURE, used here to capture which units the ORIGINAL_RESULT was measured in.'
;
-- 
-- TABLE: "CHM_ANALYTE_DETERMINATION_LIMITS" 
--

CREATE TABLE "CHM_ANALYTE_DETERMINATION_LIMITS"(
    "CHM_LIMIT_ID"           char(10)          NOT NULL,
    "ANALYTE_CODE"           varchar(7),
    "CHM_ANALYSIS_ID"        numeric(38, 0),
    "DETECTION_LOWER_LIMIT"  numeric(13, 6),
    "DETECTION_UPPER_LIMIT"  numeric(13, 6),
    "DETECTION_UNIT_CODE"    varchar(20)       NOT NULL
)
;



COMMENT ON TABLE "CHM_ANALYTE_DETERMINATION_LIMITS" IS 'Detection limits for each analysis record in CHM_ANALYSIS.'
;
COMMENT ON COLUMN "CHM_ANALYTE_DETERMINATION_LIMITS"."CHM_LIMIT_ID" IS 'PK. Unique ID generated by database for each record describing the analyte determinitations limits for a each analyte in a batch.'
;
COMMENT ON COLUMN "CHM_ANALYTE_DETERMINATION_LIMITS"."ANALYTE_CODE" IS 'FK. Unique identifier for each geochemical analyte in DIC_ANALYTE.'
;
COMMENT ON COLUMN "CHM_ANALYTE_DETERMINATION_LIMITS"."CHM_ANALYSIS_ID" IS 'FK. Unique ID for each analysis record in CHM_ANALYSIS.'
;
COMMENT ON COLUMN "CHM_ANALYTE_DETERMINATION_LIMITS"."DETECTION_LOWER_LIMIT" IS 'This column contains for each analyte the LOWEST level in parts per million or mg/kg that can be reliably detected using the specified combination of laboratory, analysis method, sample preparation technique.'
;
COMMENT ON COLUMN "CHM_ANALYTE_DETERMINATION_LIMITS"."DETECTION_UPPER_LIMIT" IS 'This column contains for each analyte the MAXIMUM level in parts per million or mg/kg that can be reliably detected using the specified combination of laboratory, analysis method, sample preparation technique.'
;
COMMENT ON COLUMN "CHM_ANALYTE_DETERMINATION_LIMITS"."DETECTION_UNIT_CODE" IS 'FK. Unique identifier in DIC_UNIT_OF_MEASURE, used here to capture which units the upper and lower limits are measured in'
;
-- 
-- TABLE: "CHM_BATCH" 
--

CREATE TABLE "CHM_BATCH"(
    "CHM_BATCH_ID"     numeric(38, 0)    NOT NULL,
    "LABORATORY_CODE"  varchar(5),
    "LAB_BATCH_ID"     varchar(50),
    "DATE_REGISTERED"  date              NOT NULL
)
;



COMMENT ON TABLE "CHM_BATCH" IS 'A table containing a batch of samples registered as a batch by a laboratory.'
;
COMMENT ON COLUMN "CHM_BATCH"."CHM_BATCH_ID" IS 'PK. Unique ID for a batch generated by database.'
;
COMMENT ON COLUMN "CHM_BATCH"."LABORATORY_CODE" IS 'FK CODE for the laboratory performing the analysis of a batch'
;
COMMENT ON COLUMN "CHM_BATCH"."LAB_BATCH_ID" IS 'The batch number issued by an analytical laboratory to identify the batch of samples, this will almost certainly be unique for each laboratory but may not be globally unique.'
;
COMMENT ON COLUMN "CHM_BATCH"."DATE_REGISTERED" IS 'Date of registration of the batch.'
;
-- 
-- TABLE: "CHM_BATCH_SAMPLE" 
--

CREATE TABLE "CHM_BATCH_SAMPLE"(
    "CHM_BATCH_ID"  numeric(38, 0)    NOT NULL,
    "SAMPLE_ID"     numeric(38, 0)    NOT NULL
)
;



COMMENT ON TABLE "CHM_BATCH_SAMPLE" IS 'Linking table to record which samples were batched together'
;
COMMENT ON COLUMN "CHM_BATCH_SAMPLE"."CHM_BATCH_ID" IS 'FK. Unique ID for a batch as stored in the CHM_BATCH table.'
;
COMMENT ON COLUMN "CHM_BATCH_SAMPLE"."SAMPLE_ID" IS 'FK. This is the unique ID from the CHM_SAMPLE table.'
;
-- 
-- TABLE: "CHM_SAMPLE" 
--

CREATE TABLE "CHM_SAMPLE"(
    "SAMPLE_ID"       numeric(38, 0)    NOT NULL,
    "SITE_ID"         numeric(38, 0)    NOT NULL,
    "COLLECTED_DATE"  timestamp
)
;



COMMENT ON TABLE "CHM_SAMPLE" IS 'Index table of geochemical samples.'
;
COMMENT ON COLUMN "CHM_SAMPLE"."SAMPLE_ID" IS 'Unique Identifier for a sample. This is a primary key of this table.'
;
COMMENT ON COLUMN "CHM_SAMPLE"."SITE_ID" IS 'FK. Unique Identifier for a collection site in the CHM_SITE table.'
;
COMMENT ON COLUMN "CHM_SAMPLE"."COLLECTED_DATE" IS 'Date (and time if known) that the sample was collected in the field'
;
-- 
-- TABLE: "CHM_SITE" 
--

CREATE TABLE "CHM_SITE"(
    "SITE_ID"    numeric(38, 0)    NOT NULL,
    "X"          numeric(10, 0)    NOT NULL,
    "Y"          numeric(10, 0)    NOT NULL,
    "EPSG_CODE"  varchar(10)       NOT NULL
)
;



COMMENT ON TABLE "CHM_SITE" IS 'Location from which a sample was collected.'
;
COMMENT ON COLUMN "CHM_SITE"."SITE_ID" IS 'Unique Identifier for a collection site. This is a primary key of this table.'
;
COMMENT ON COLUMN "CHM_SITE"."X" IS 'The original X coordinate.'
;
COMMENT ON COLUMN "CHM_SITE"."Y" IS 'The original Y coordinate.'
;
COMMENT ON COLUMN "CHM_SITE"."EPSG_CODE" IS 'The Coordinate Reference System code for the original coordinate system.'
;
-- 
-- TABLE: "DIC_ANALYSIS_METHOD" 
--

CREATE TABLE "DIC_ANALYSIS_METHOD"(
    "CODE"         varchar(7)      NOT NULL,
    "TRANSLATION"  varchar(50)     NOT NULL,
    "DESCRIPTION"  varchar(250)    NOT NULL,
    "STATUS"       char(1)         DEFAULT 'C' NOT NULL
)
;



COMMENT ON TABLE "DIC_ANALYSIS_METHOD" IS 'Dictionary containing methods of chemical analysis.'
;
COMMENT ON COLUMN "DIC_ANALYSIS_METHOD"."CODE" IS 'PK. Identifier for each method, text value up to 7 characters long.'
;
COMMENT ON COLUMN "DIC_ANALYSIS_METHOD"."TRANSLATION" IS 'General description of the method and the types of values it contains, up to 50 characters long.'
;
COMMENT ON COLUMN "DIC_ANALYSIS_METHOD"."DESCRIPTION" IS 'Detailed description of the method and the types of values it contains, up to 250 characters long.'
;
COMMENT ON COLUMN "DIC_ANALYSIS_METHOD"."STATUS" IS 'Status of the unit. This has a check constraint in C:Current, O:Obsolete.'
;
-- 
-- TABLE: "DIC_ANALYSIS_PREP" 
--

CREATE TABLE "DIC_ANALYSIS_PREP"(
    "CODE"         varchar(5)      NOT NULL,
    "TRANSLATION"  varchar(60)     NOT NULL,
    "DESCRIPTION"  varchar(250)    NOT NULL,
    "STATUS"       char(1)         DEFAULT 'C' NOT NULL
)
;



COMMENT ON TABLE "DIC_ANALYSIS_PREP" IS 'A dictionary of preparations that are undertaken in a laboratory on a batch of samples'
;
COMMENT ON COLUMN "DIC_ANALYSIS_PREP"."CODE" IS 'PK. Identifier for each preparation method, text value up to 5 characters long.'
;
COMMENT ON COLUMN "DIC_ANALYSIS_PREP"."TRANSLATION" IS 'Short description of the analysis preparation used.'
;
COMMENT ON COLUMN "DIC_ANALYSIS_PREP"."DESCRIPTION" IS 'Full description of the analysis preparation used, upto 250 characters.'
;
COMMENT ON COLUMN "DIC_ANALYSIS_PREP"."STATUS" IS 'Status of the unit. This has a check constraint in C:Current, O:Obsolete.'
;
-- 
-- TABLE: "DIC_ANALYTE" 
--

CREATE TABLE "DIC_ANALYTE"(
    "CODE"                varchar(7)       NOT NULL,
    "QUANTITY_UNIT_CODE"  varchar(20),
    "TRANSLATION"         varchar(25)      NOT NULL,
    "DESCRIPTION"         varchar(240)     NOT NULL,
    "STATUS"              char(1)          DEFAULT 'C' NOT NULL,
    "ATOMIC_NUMBER"       numeric(3, 0),
    "WEIGHT"              numeric(6, 3)
)
;



COMMENT ON TABLE "DIC_ANALYTE" IS 'Dictionary list of geochemical analytes'
;
COMMENT ON COLUMN "DIC_ANALYTE"."CODE" IS 'PK. Unique identifier for each geochemical analyte, up to 7 characters.'
;
COMMENT ON COLUMN "DIC_ANALYTE"."QUANTITY_UNIT_CODE" IS 'Identifier of the measurement unit. This is a primary key of this table.'
;
COMMENT ON COLUMN "DIC_ANALYTE"."STATUS" IS 'Status of the unit. This has a check constraint in C:Current, O:Obsolete.'
;
-- 
-- TABLE: "DIC_LABORATORY" 
--

CREATE TABLE "DIC_LABORATORY"(
    "CODE"         varchar(5)      NOT NULL,
    "TRANSLATION"  varchar(60)     NOT NULL,
    "DESCRIPTION"  varchar(200)    NOT NULL,
    "STATUS"       char(1)         DEFAULT 'C' NOT NULL
)
;



COMMENT ON TABLE "DIC_LABORATORY" IS 'Dictionary containing a list of laboratories that could be used for chemical analysis.'
;
COMMENT ON COLUMN "DIC_LABORATORY"."CODE" IS 'PK. Up to 5 character code for a laboratory.'
;
COMMENT ON COLUMN "DIC_LABORATORY"."TRANSLATION" IS 'Name of the laboratory, short text field limited to 60 characters.'
;
COMMENT ON COLUMN "DIC_LABORATORY"."DESCRIPTION" IS 'Full description of the laboratory, up to 200 characters.'
;
COMMENT ON COLUMN "DIC_LABORATORY"."STATUS" IS 'Status of the unit. This has a check constraint in C:Current, O:Obsolete.'
;
-- 
-- TABLE: "DIC_UNIT_OF_MEASURE" 
--

CREATE TABLE "DIC_UNIT_OF_MEASURE"(
    "CODE"                     varchar(20)       NOT NULL,
    "DESCRIPTION"              varchar(200)      NOT NULL,
    "TRANSLATION"              varchar(80),
    "ABBREVIATION"             varchar(15),
    "EPSG_CODE"                varchar(20),
    "DATA_SOURCE"              varchar(20),
    "TARGET_UOM_CODE"          varchar(20),
    "CONV_FACTOR_NUMERATOR"    numeric(10, 5),
    "CONV_FACTOR_DENOMINATOR"  numeric(10, 5),
    "UNIT_OF_MEAS_DIMENSION"   varchar(50)       
                               CHECK (UNIT_OF_MEAS_DIMENSION in 
('all','length','angle','scale','volumetric rate','mass rate','temperature','mass','volume','charge per mass',
'time','Dimensionless','electric conductivity','volumetric mass','turbidity','area', 'density', '?', 'pressure',
'ratio', 'resistivity', 'slowness', 'velocity'
)),
    "REMARKS"                  varchar(255),
    "ORIG_INFORMATION_SOURCE"  varchar(255),
    "STATUS"                   char(1)           DEFAULT 'C' NOT NULL
                               CHECK (status in ('C','O'))
)
;



COMMENT ON TABLE "DIC_UNIT_OF_MEASURE" IS 'Dictionary table to store list of measurement units'
;
COMMENT ON COLUMN "DIC_UNIT_OF_MEASURE"."CODE" IS 'Identifier of the measurement unit. This is a primary key of this table.'
;
COMMENT ON COLUMN "DIC_UNIT_OF_MEASURE"."DESCRIPTION" IS 'Full description of the CODE value.'
;
COMMENT ON COLUMN "DIC_UNIT_OF_MEASURE"."TRANSLATION" IS 'A short translation of the CODE value.'
;
COMMENT ON COLUMN "DIC_UNIT_OF_MEASURE"."ABBREVIATION" IS 'Abbreviation  code used to respresent a measurement.'
;
COMMENT ON COLUMN "DIC_UNIT_OF_MEASURE"."EPSG_CODE" IS 'EPSG code for a unit'
;
COMMENT ON COLUMN "DIC_UNIT_OF_MEASURE"."DATA_SOURCE" IS 'Source of the data'
;
COMMENT ON COLUMN "DIC_UNIT_OF_MEASURE"."TARGET_UOM_CODE" IS 'Target Unit of Measure code.'
;
COMMENT ON COLUMN "DIC_UNIT_OF_MEASURE"."CONV_FACTOR_NUMERATOR" IS 'Factor numerator to convert into Target code'
;
COMMENT ON COLUMN "DIC_UNIT_OF_MEASURE"."CONV_FACTOR_DENOMINATOR" IS 'Factor denominator to convert into Target code'
;
COMMENT ON COLUMN "DIC_UNIT_OF_MEASURE"."UNIT_OF_MEAS_DIMENSION" IS 'The dimension or feature for which this unit is used. For example length, pressure, temperature, angle etc.'
;
COMMENT ON COLUMN "DIC_UNIT_OF_MEASURE"."REMARKS" IS 'General remarks or comments not covered by other fields'
;
COMMENT ON COLUMN "DIC_UNIT_OF_MEASURE"."ORIG_INFORMATION_SOURCE" IS 'Original information source.'
;
COMMENT ON COLUMN "DIC_UNIT_OF_MEASURE"."STATUS" IS 'Status of the unit. This has a check constraint in C:Current, O:Obsolete.'
;
-- 
-- INDEX: "PK6" 
--

CREATE UNIQUE INDEX "PK6" ON "CHM_ANALYSIS"("CHM_ANALYSIS_ID")
;
-- 
-- INDEX: "Ref38" 
--

CREATE INDEX "Ref38" ON "CHM_ANALYSIS"("CHM_BATCH_ID")
;
-- 
-- INDEX: "Ref79" 
--

CREATE INDEX "Ref79" ON "CHM_ANALYSIS"("METHOD_CODE")
;
-- 
-- INDEX: "Ref810" 
--

CREATE INDEX "Ref810" ON "CHM_ANALYSIS"("PREPERATION_CODE")
;
-- 
-- INDEX: "PK10" 
--

CREATE UNIQUE INDEX "PK10" ON "CHM_ANALYTE_DETERMINATION"("CHM_DETERMINATION_ID")
;
-- 
-- INDEX: "Ref529" 
--

CREATE INDEX "Ref529" ON "CHM_ANALYTE_DETERMINATION"("SAMPLE_ID", "CHM_BATCH_ID")
;
-- 
-- INDEX: "Ref3860" 
--

CREATE INDEX "Ref3860" ON "CHM_ANALYTE_DETERMINATION"("ORIGINAL_UNIT_CODE")
;
-- 
-- INDEX: "Ref1328" 
--

CREATE INDEX "Ref1328" ON "CHM_ANALYTE_DETERMINATION"("CHM_LIMIT_ID")
;
-- 
-- INDEX: "PK13" 
--

CREATE UNIQUE INDEX "PK13" ON "CHM_ANALYTE_DETERMINATION_LIMITS"("CHM_LIMIT_ID")
;
-- 
-- INDEX: "Ref3859" 
--

CREATE INDEX "Ref3859" ON "CHM_ANALYTE_DETERMINATION_LIMITS"("DETECTION_UNIT_CODE")
;
-- 
-- INDEX: "Ref612" 
--

CREATE INDEX "Ref612" ON "CHM_ANALYTE_DETERMINATION_LIMITS"("CHM_ANALYSIS_ID")
;
-- 
-- INDEX: "Ref1113" 
--

CREATE INDEX "Ref1113" ON "CHM_ANALYTE_DETERMINATION_LIMITS"("ANALYTE_CODE")
;
-- 
-- INDEX: "PK3" 
--

CREATE UNIQUE INDEX "PK3" ON "CHM_BATCH"("CHM_BATCH_ID")
;
-- 
-- INDEX: "Ref1431" 
--

CREATE INDEX "Ref1431" ON "CHM_BATCH"("LABORATORY_CODE")
;
-- 
-- INDEX: "PK5" 
--

CREATE UNIQUE INDEX "PK5" ON "CHM_BATCH_SAMPLE"("CHM_BATCH_ID", "SAMPLE_ID")
;
-- 
-- INDEX: "Ref324" 
--

CREATE INDEX "Ref324" ON "CHM_BATCH_SAMPLE"("CHM_BATCH_ID")
;
-- 
-- INDEX: "Ref225" 
--

CREATE INDEX "Ref225" ON "CHM_BATCH_SAMPLE"("SAMPLE_ID")
;
-- 
-- INDEX: "PK2" 
--

CREATE UNIQUE INDEX "PK2" ON "CHM_SAMPLE"("SAMPLE_ID")
;
-- 
-- INDEX: "Ref11" 
--

CREATE INDEX "Ref11" ON "CHM_SAMPLE"("SITE_ID")
;
-- 
-- INDEX: "PK1" 
--

CREATE UNIQUE INDEX "PK1" ON "CHM_SITE"("SITE_ID")
;
-- 
-- INDEX: "PK7" 
--

CREATE UNIQUE INDEX "PK7" ON "DIC_ANALYSIS_METHOD"("CODE")
;
-- 
-- INDEX: "PK8" 
--

CREATE UNIQUE INDEX "PK8" ON "DIC_ANALYSIS_PREP"("CODE")
;
-- 
-- INDEX: "PK11" 
--

CREATE UNIQUE INDEX "PK11" ON "DIC_ANALYTE"("CODE")
;
-- 
-- INDEX: "Ref3864" 
--

CREATE INDEX "Ref3864" ON "DIC_ANALYTE"("QUANTITY_UNIT_CODE")
;
-- 
-- INDEX: "PK8_1" 
--

CREATE UNIQUE INDEX "PK8_1" ON "DIC_LABORATORY"("CODE")
;
-- 
-- INDEX: "DIC_UNIT_OF_MEASURE_PK" 
--

CREATE UNIQUE INDEX "DIC_UNIT_OF_MEASURE_PK" ON "DIC_UNIT_OF_MEASURE"("CODE")
;
-- 
-- INDEX: "DIC_UNIT_OF_MEASURE_FK1" 
--

CREATE INDEX "DIC_UNIT_OF_MEASURE_FK1" ON "DIC_UNIT_OF_MEASURE"("TARGET_UOM_CODE")
;
-- 
-- TABLE: "CHM_ANALYSIS" 
--

ALTER TABLE "CHM_ANALYSIS" ADD CONSTRAINT "RefCHM_BATCH8" 
    FOREIGN KEY ("CHM_BATCH_ID")
    REFERENCES "CHM_BATCH"("CHM_BATCH_ID")
;

ALTER TABLE "CHM_ANALYSIS" ADD CONSTRAINT "RefDIC_ANALYSIS_METHOD9" 
    FOREIGN KEY ("METHOD_CODE")
    REFERENCES "DIC_ANALYSIS_METHOD"("CODE")
;

ALTER TABLE "CHM_ANALYSIS" ADD CONSTRAINT "RefDIC_ANALYSIS_PREP10" 
    FOREIGN KEY ("PREPERATION_CODE")
    REFERENCES "DIC_ANALYSIS_PREP"("CODE")
;


-- 
-- TABLE: "CHM_ANALYTE_DETERMINATION" 
--

ALTER TABLE "CHM_ANALYTE_DETERMINATION" ADD CONSTRAINT "RefCHM_BATCH_SAMPLE29" 
    FOREIGN KEY ("CHM_BATCH_ID", "SAMPLE_ID")
    REFERENCES "CHM_BATCH_SAMPLE"("CHM_BATCH_ID", "SAMPLE_ID")
;

ALTER TABLE "CHM_ANALYTE_DETERMINATION" ADD CONSTRAINT "RefDIC_UNIT_OF_MEASURE60" 
    FOREIGN KEY ("ORIGINAL_UNIT_CODE")
    REFERENCES "DIC_UNIT_OF_MEASURE"("CODE")
;

ALTER TABLE "CHM_ANALYTE_DETERMINATION" ADD CONSTRAINT "RefCHM_ANALYTE_DETERMINATION_LIMITS28" 
    FOREIGN KEY ("CHM_LIMIT_ID")
    REFERENCES "CHM_ANALYTE_DETERMINATION_LIMITS"("CHM_LIMIT_ID")
;


-- 
-- TABLE: "CHM_ANALYTE_DETERMINATION_LIMITS" 
--

ALTER TABLE "CHM_ANALYTE_DETERMINATION_LIMITS" ADD CONSTRAINT "RefDIC_UNIT_OF_MEASURE59" 
    FOREIGN KEY ("DETECTION_UNIT_CODE")
    REFERENCES "DIC_UNIT_OF_MEASURE"("CODE")
;

ALTER TABLE "CHM_ANALYTE_DETERMINATION_LIMITS" ADD CONSTRAINT "RefCHM_ANALYSIS12" 
    FOREIGN KEY ("CHM_ANALYSIS_ID")
    REFERENCES "CHM_ANALYSIS"("CHM_ANALYSIS_ID")
;

ALTER TABLE "CHM_ANALYTE_DETERMINATION_LIMITS" ADD CONSTRAINT "RefDIC_ANALYTE13" 
    FOREIGN KEY ("ANALYTE_CODE")
    REFERENCES "DIC_ANALYTE"("CODE")
;


-- 
-- TABLE: "CHM_BATCH" 
--

ALTER TABLE "CHM_BATCH" ADD CONSTRAINT "RefDIC_LABORATORY31" 
    FOREIGN KEY ("LABORATORY_CODE")
    REFERENCES "DIC_LABORATORY"("CODE")
;


-- 
-- TABLE: "CHM_BATCH_SAMPLE" 
--

ALTER TABLE "CHM_BATCH_SAMPLE" ADD CONSTRAINT "RefCHM_BATCH24" 
    FOREIGN KEY ("CHM_BATCH_ID")
    REFERENCES "CHM_BATCH"("CHM_BATCH_ID")
;

ALTER TABLE "CHM_BATCH_SAMPLE" ADD CONSTRAINT "RefCHM_SAMPLE25" 
    FOREIGN KEY ("SAMPLE_ID")
    REFERENCES "CHM_SAMPLE"("SAMPLE_ID")
;


-- 
-- TABLE: "CHM_SAMPLE" 
--

ALTER TABLE "CHM_SAMPLE" ADD CONSTRAINT "RefCHM_SITE1" 
    FOREIGN KEY ("SITE_ID")
    REFERENCES "CHM_SITE"("SITE_ID")
;


-- 
-- TABLE: "DIC_ANALYTE" 
--

ALTER TABLE "DIC_ANALYTE" ADD CONSTRAINT "RefDIC_UNIT_OF_MEASURE64" 
    FOREIGN KEY ("QUANTITY_UNIT_CODE")
    REFERENCES "DIC_UNIT_OF_MEASURE"("CODE")
;


-- 
-- TABLE: "DIC_UNIT_OF_MEASURE" 
--

ALTER TABLE "DIC_UNIT_OF_MEASURE" ADD CONSTRAINT "DIC_UNIT_OF_MEASURE_FK1" 
    FOREIGN KEY ("TARGET_UOM_CODE")
    REFERENCES "DIC_UNIT_OF_MEASURE"("CODE")
;


